import 'package:att_loneworker/core/constants/routes/routes_name.dart';
import 'package:flutter/material.dart';

import '../../../model/home_service_item/home_service_item.dart';
import '../../../view/alarm_settings/alarm_settings_view.dart';
import '../../../view/battery_settings/battery_settings_view.dart';
import '../../../view/tilt_alert_settings/tilt_alert_settings_view.dart';
import '../colors.dart';
import '../localization/localization_keys_constants.dart';

final appHomeServiceList = [
  HomeServiceItem(
      id: 1,
      title: LocalizationKeys.ALARM_SETTINGS,
      isSelected: false,
      iconCode: Icons.security.codePoint,
      iconColorValue: AppColors.primary.value,
      navigateScreen: AppRoutesNames.alarmSettingsView),
  HomeServiceItem(
    id: 2,
    title: LocalizationKeys.BATTERY_ALARM,
    isSelected: false,
    iconCode: Icons.battery_alert_sharp.codePoint,
    iconColorValue: AppColors.primary.value,
    navigateScreen: AppRoutesNames.batterySettingsView,
  ),
  HomeServiceItem(
    id: 3,
    title: LocalizationKeys.TILT_ALERT,
    isSelected: false,
    iconCode: Icons.accessibility_new_rounded.codePoint,
    iconColorValue: AppColors.primary.value,
    navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  ),
  HomeServiceItem(
    id: 4,
    title: LocalizationKeys.LOCATION_SETTINGS,
    isSelected: false,
    iconCode: Icons.location_on.codePoint,
    iconColorValue: AppColors.primary.value,
    navigateScreen: AppRoutesNames.locationSettingsSettingsView,
  ),

  //////////////

  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
  // HomeServiceItem(
  //     id: 1,
  //     title: LocalizationKeys.ALARM_SETTINGS,
  //     isSelected: false,
  //     iconCode: Icons.security.codePoint,
  //     iconColorValue: AppColors.primary.value,
  //     navigateScreen: AppRoutesNames.alarmSettingsView),
  // HomeServiceItem(
  //   id: 2,
  //   title: LocalizationKeys.BATTERY_ALARM,
  //   isSelected: false,
  //   iconCode: Icons.battery_alert_sharp.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.batterySettingsView,
  // ),
  // HomeServiceItem(
  //   id: 3,
  //   title: LocalizationKeys.TILT_ALERT,
  //   isSelected: false,
  //   iconCode: Icons.accessibility_new_rounded.codePoint,
  //   iconColorValue: AppColors.primary.value,
  //   navigateScreen: AppRoutesNames.tiltAlertSettingsView,
  // ),
];
