// ignore_for_file: constant_identifier_names

abstract class LocalizationKeys {
  // COMMON
  static const NAME_HOME = "NAME_HOME";
  static const NAME_SETTINGS = "NAME_SETTINGS";
  static const HOME_APPBAR_TITLE = "HOME.APPBAR_TITLE";
  static const SECONDS = "SECONDS";
  static const CLOSE = "CLOSE";
  static const LOCATION_PERMISSION = "LOCATION_PERMISSION";
  static const PERMISSION_REQUIRED = "PERMISSION_REQUIRED";
  static const OPEN_SETTINGS = "OPEN_SETTINGS";

  //LOGIN
  static const LOGIN_USERNAME = "LOGIN.USERNAME";
  static const LOGIN_PASSWORD = 'LOGIN.PASSWORD';
  static const LOGIN_REMEMBER_ME = 'LOGIN.REMEMBER_ME';
  static const LOGIN_LOGIN = 'LOGIN.LOGIN';
  static const LOGIN_USERNAME_EMPTY = 'LOGIN.USERNAME_EMPTY';
  static const LOGIN_PASSWORD_EMPTY = 'LOGIN.PASSWORD_EMPTY';
  static const LOGOUT = 'LOGIN.LOGOUT';

  //HOME

  static const CURRENT_LOCATION = 'HOME.CURRENT_LOCATION';
  static const SERVICES = 'HOME.SERVICES';
  static const GPS_ENABLED = 'HOME.GPS_ENABLED';
  static const ALARM_SETTINGS = 'HOME.ALARM_SETTINGS';
  static const ALARM_VOLUME = 'HOME.ALARM_VOLUME';
  static const BATTERY_SETTINGS = 'HOME.BATTERY_SETTINGS';
  static const BATTERY_ALARM = 'HOME.BATTERY_ALARM';
  static const BATTERY_CONDITION = 'HOME.BATTERY_CONDITION';
  static const TILT_ALERT = 'HOME.TILT_ALERT';
  static const LOCATION_SETTINGS = 'HOME.LOCATION_SETTINGS';

  // SETTINGS
  static const SETTINGS_VIEW__APP_BAR_TITLE = 'SETTINGS.APP_BAR_TITLE';

  //BATTERY SETTINGS

  static const DURATION_IN_BATTERY_ALARM_SITUATION =
      'BATTERY_SETTINGS.DURATION_IN_BATTERY_ALARM_SITUATION';

  //TILT SETTINGS

  static const TILT_ANGLE = 'TILT_SETTINGS.TILT_ANGLE';
  static const DURATION_IN_ALARM_SITUATION =
      'TILT_SETTINGS.DURATION_IN_ALARM_SITUATION';
  static const DURATION_OF_THE_PRE_ALARM =
      'TILT_SETTINGS.DURATION_OF_THE_PRE_ALARM';

  //LOCATION SETTINGS

  static const LOCATION_DURATION =
      'LOCATION_SETTINGS.DURATION_IN_LOCATION_ALARM_SITUATION';
}
